apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-tenant-demo
  namespace: default
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: capi-tenant-demo
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: capi-tenant-demo
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: capi-tenant-demo
  namespace: default
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: null
      repo: null
      version: null
    values: |-
      service:
        type: LoadBalancer
  kubernetesVersion: v1.26.14
