apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: tenant-01
  namespace: vcluster-tenant-01
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: tenant-01
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: tenant-01
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: tenant-01
  namespace: vcluster-tenant-01
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: null
      repo: null
      version: null
      # version: "0.19.5"
    values: |-
      service:
        type: LoadBalancer
  kubernetesVersion: v1.26.14
