# enabling the metrics server proxy
proxy:
  metricsServer:
    nodes:
      enabled: true
    pods:
      enabled: true

sync:
  # enable Node synchronization for DaemonSet support
  nodes:
    enabled: true
    syncAllNodes: true

  # enable Ingress resources synchronization
  ingresses:
    enabled: true
  
  serviceaccounts:
    enabled: true
    
  # enable synchronization of the Network Policies
  # networkpolicies:
  #   enabled: true

  # enable synchronization of GCP bucket config connector resources
  generic:
    clusterRole:
      extraRules:
        - apiGroups: ["apiextensions.k8s.io"]
          resources: ["customresourcedefinitions"]
          verbs: ["get", "list", "watch"]
    role:
      extraRules:
        - apiGroups: ["storage.cnrm.cloud.google.com"]
          resources: ["storagebuckets"]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
    config: |-
      version: v1beta1
      export:
        - kind: StorageBucket
          apiVersion: storage.cnrm.cloud.google.com/v1beta1

multiNamespaceMode:
  enabled: true
