---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-variables
  namespace: capg-system
type: Opaque
data:
  credentials.json: Zm9vCg==
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
 name: gcp
 namespace: capg-system
spec:
 version: v1.6.0
 configSecret:
   name: gcp-variables