apiVersion: v1
kind: Namespace
metadata:
  name: vcluster-tenant-01
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster-tenant-01
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vcluster
      sourceRef:
        kind: HelmRepository
        name: loft-sh
      version: "0.19.5"
  interval: 1h0m0s
  releaseName: kube-prometheus-stack
  targetNamespace: vcluster-tenant-01